workspace "Nit"
    architecture "x86_64"
    configurations { "Debug", "Release" }
    startproject "GameEditorApp"

include "NitDirectories.lua"

group "Engine"
    include "Engine/NitCore/NitCoreProject.lua"
    include "Engine/NitMath/NitMathProject.lua"
    include "Engine/NitRender/NitRenderProject.lua"
    include "Engine/Nit/NitProject.lua"
    include "Engine/NitEditor/NitEditorProject.lua"
group ""

group "Game"
    include "Game/Game/GameProject.lua"
    include "Game/GameEditorApp/GameEditorAppProject.lua"
    include "Game/GameApp/GameAppProject.lua"
    include "Game/RenderSandbox/RenderSandboxProject.lua"
group ""

group "ThirdParty"
    include "ThirdParty/GLFW/GLFWProject.lua"
    include "ThirdParty/GLAD/GLADProject.lua"
    include "ThirdParty/RTTR/RTTRProject.lua"
    include "ThirdParty/ImGui/ImGuiProject.lua"
    include "ThirdParty/ImGuizmo/ImGuizmoProject.lua"
    include "ThirdParty/OpenAL/OpenALProject.lua"
    include "ThirdParty/Box2D/Box2DProject.lua"
group ""